// countries.js

const africanCountries = [
  "Nigeria",
  "Kenya",
  "South Africa",
  "Ghana",
  "Ethiopia",
  "Egypt",
  "Uganda",
  "Tanzania",
  "Morocco",
  "Senegal",
  "Cameroon",
  "Ivory Coast",
  "Zimbabwe",
  "Zambia",
  "Mali",
  "Sudan",
  "Algeria",
  "Tunisia",
  "Botswana",
  "Namibia",
  "Rwanda",
  "Burundi",
  "Mozambique",
  "Angola",
  "Somalia",
  "Chad",
  "Niger",
  "Libya",
  "Sierra Leone",
  "Liberia",
  "Malawi",
  "Mauritius",
  "Madagascar",
  "Eritrea",
  "Djibouti",
  "Lesotho",
  "Eswatini",
  "Gambia",
  "Guinea",
  "Guinea-Bissau",
  "Central African Republic",
  "Congo (DRC)",
  "Congo (Republic)",
  "Gabon",
  "Seychelles",
  "Cape Verde",
  "Equatorial Guinea",
  "South Sudan",
  "Mauritania",
  "Western Sahara"
];

// Export for use
export default africanCountries;
